### ISSUE TITLE
npm package doesn't update to version 1.0.2

### ISSUE THREAD

**Issue by armada45-pixel** [DevTobias/elysia-helmet#4]
npm package doesn't update to version 1.0.2
![image](https://github.com/DevTobias/elysia-helmet/assets/59261678/da86cc6a-029b-46fb-858c-52655dfbcbb9)

**Comment by MYKEU** [comment]
@DevTobias can we please get this published 🙏

**Comment by shrinathprabhu** [comment]
Hey @DevTobias can we publish this please? The version 1.0.1 is causing issues with Elysia 0.8 and 1.0.2 is not present in npm.

**Comment by DevTobias** [comment]
Sorry for the delay :) Should be published now. @MYKEU @shrinathprabhu
