### ISSUE TITLE
Missing types on published package

### ISSUE THREAD

**Issue by nxht** [DevTobias/elysia-helmet#7]
Not sure if it's intended or not but it seems `helmet.d.ts` and all the policies typings are missing on the published package, unlike the build result when I tested locally.

**Comment by Chooks22** [comment]
Types seems to come from [helmet.ts](https://github.com/DevTobias/elysia-helmet/blob/b1bb82587776ab992a02c99127203d559339db5d/src/helmet.ts), but only the [index.ts files are included in the package](https://github.com/DevTobias/elysia-helmet/blob/main/package.json#L20-L21).

**Comment by DevTobias** [comment]
Should be resolved in the newest release :) @nxht
